version: 2.1
orbs:
  provar: provartesting/provar@1.9.10
           
workflows:
  version: 2.1
  run_all:
    jobs:
      - provar/run_provar:
          majorversion: "1.9.10"
          minorversion: "02"
          url: "download.provartesting.com"
          name: running test cases using ant build.xml
          steps:
            - run: ant -Dprovar.home="/home/circleci/project/Provar_Home" -f DemoProject/build.xml